version: '3.3'
services:
    User_api:
        ports:
            - '5000:5000'
        volumes:
            - 'Upsonic_Volume:/app/Upsonic'
        image: ghcr.io/upsonic-database/api:latest
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 500M           
        command: upsonic api --host=0.0.0.0 --port=5000
        environment:
            folder: "" # "/"
            password : "Upsonic"
            threads: 4
            restricted: "database_list,database_delete,database_pop,database_pop_all,database_delete_all,debug,info,warning,error,exception"

            maximum_database_amount: 200
            maximum_key_amount: 5000

            rate_limit : "400 per hour, 80 per minute"
            key_lenght : 100
            value_lenght : 4000
            database_name_lenght : 50
            maximum_database_amount_user: 1
            maximum_key_amount_user: 25


    User_api_Pro:
        ports:
            - '5001:5000'
        volumes:
            - 'Upsonic_Volume_Pro:/app/Upsonic'
            - 'Upsonic_Volume_Access:/app'
        image: ghcr.io/upsonic-database/api:latest
        deploy:
          resources:
            limits:
              cpus: '1'
              memory: 500M             
        command: upsonic api --host=0.0.0.0 --port=5000
        environment:
            folder: "" # "/"
            password : "Upsonic"
            threads: 4
            restricted: "database_list,database_delete,database_pop,database_pop_all,database_delete_all,debug,info,warning,error,exception"

            maximum_database_amount: 2500
            maximum_key_amount: 10000

            rate_limit : "1600 per hour, 160 per minute"
            key_lenght : 100
            value_lenght : 8000
            database_name_lenght : 100
            maximum_database_amount_user: 25
            maximum_key_amount_user: 100         

            access_key: True
            access_key_folder: "/app" # "/"
            access_key_lists: "Upsonic" # "aa, 231"
            access_key_lists_cache: 60              



    Admin_api:
        ports:
            - '4999:5000'
        volumes:
            - 'Upsonic_Volume:/app/Upsonic'
        image: ghcr.io/upsonic-database/api:latest
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 500M             
        command: upsonic api --host=0.0.0.0 --port=5000
        environment:
            folder: "" # "/"
            password : "Upsonic"
            threads: 4
    

            rate_limit : "400 per hour, 40 per minute"
            key_lenght : 100
            value_lenght : 1000
            database_name_lenght : 50
            maximum_database_amount: 200
            maximum_key_amount: 500
            maximum_database_amount_user: 1
            maximum_key_amount_user: 25

            access_key: False
            access_key_folder: "" # "/"
            access_key_lists: "" # "aa, 231"
            access_key_lists_cache: 60           




    Admin_api_pro:
        ports:
            - '4998:5000'
        volumes:
            - 'Upsonic_Volume_Pro:/app/Upsonic'
        image: ghcr.io/upsonic-database/api:latest
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 500M             
        command: upsonic api --host=0.0.0.0 --port=5000
        environment:
            folder: "" # "/"
            password : "Upsonic"
            threads: 4


            rate_limit : "400 per hour, 40 per minute"
            key_lenght : 100
            value_lenght : 10000
            database_name_lenght : 50
            maximum_database_amount: 200
            maximum_key_amount: 500
            maximum_database_amount_user: 5
            maximum_key_amount_user: 50

            access_key: False
            access_key_folder: "" # "/"
            access_key_lists: "" # "aa, 231"
            access_key_lists_cache: 60     

    Admin_api_pro_access:
        ports:
            - '4997:5000'
        volumes:
            - 'Upsonic_Volume_Access:/app/Upsonic'
        image: ghcr.io/upsonic-database/api:latest
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 500M             
        command: upsonic api --host=0.0.0.0 --port=5000
        environment:
            folder: "" # "/"
            password : "Upsonic"
            threads: 4


            rate_limit : "400 per hour, 40 per minute"
            key_lenght : 100
            value_lenght : 10000
            database_name_lenght : 50
            maximum_database_amount: 200
            maximum_key_amount: 500
            maximum_database_amount_user: 5
            maximum_key_amount_user: 50

            access_key: False
            access_key_folder: "" # "/"
            access_key_lists: "" # "aa, 231"
            access_key_lists_cache: 60     



    Admin_web:
        ports:
            - '4007:5000'
        volumes:
            - 'Upsonic_Volume:/app/Upsonic'
        image: ghcr.io/upsonic-database/web:latest
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 500M             
        command: upsonic web Upsonic --host=0.0.0.0 --port=5000

    Admin_pro_web:
        ports:
            - '4006:5000'
        volumes:
            - 'Upsonic_Volume_Pro:/app/Upsonic'
        image: ghcr.io/upsonic-database/web:latest
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 500M          
        command: upsonic web Upsonic --host=0.0.0.0 --port=5000


volumes:
  Upsonic_Volume:
  Upsonic_Volume_Pro:
  Upsonic_Volume_Access:
