version: '3.3'
services:
    User_api:
        ports:
            - '5000:5000'
        volumes:
            - 'KOT_Volume:/app/KOT'
        image: ghcr.io/kot-database/api:latest
        command: KOT api --host=0.0.0.0 --port=5000
        environment:
            folder: "" # "/"
            password : "USER_PASS"
            restricted: "set,delete,get_all,database_list,database_delete,database_pop,database_pop_all,database_delete_all,debug,info,warning,error,exception"

            maximum_database_amount: 100
            maximum_key_amount: 4000

            rate_limit : "1600 per hour, 160 per minute"
            key_lenght : 2000
            value_lenght : 4000
            database_name_lenght : 100
            maximum_database_amount_user: 100
            maximum_key_amount_user: 4000


    admin_api:
        ports:
            - '5001:5000'
        volumes:
            - 'KOT_Volume:/app/KOT'
        image: ghcr.io/kot-database/api:latest
        command: KOT api --host=0.0.0.0 --port=5000
        environment:
            folder: "" # "/"
            password : "ADMIN_PASS"
            restricted: "get_all,database_list,database_delete,database_pop,database_pop_all,database_delete_all,debug,info,warning,error,exception"

            maximum_database_amount: 100
            maximum_key_amount: 4000

            rate_limit : "1600 per hour, 160 per minute"
            key_lenght : 2000
            value_lenght : 4000
            database_name_lenght : 100
            maximum_database_amount_user: 100
            maximum_key_amount_user: 4000


volumes:
  KOT_Volume: