name: After Deploy Test

on:
  workflow_run:
    workflows: ["Deploys"]
    types:
      - completed 
  workflow_dispatch: 

jobs:
  pypi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install kot kot_api kot_gui kot_web --user
