name: After Deploy Test Every 15 Minute

on:
  workflow_run:
    workflows: ["Deploys"]
    types:
      - completed 
  schedule:
    - cron:  '*/15 * * * *'      
  workflow_dispatch: 

jobs:
  pypi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install kot kot_api kot_gui kot_web --no-cache --upgrade

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with pytest
        run: |
          cd ..
          pytest KOT/tests/ -v


  docker:
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        docker pull ghcr.io/onuratakan/api:latest
    - name: Test with pytest
      run: |
        pytest tests/published_docker.py -v          