name: After Deploy Test Every 15 Minute

on:
  schedule:
    - cron:  '*/15 * * * *'      
  workflow_dispatch: 

  workflow_run:
    workflows: ["Deploys"]
    types:
      - completed  

jobs:


  tagext:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Getting Tag
        id: tag_extractor
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - name: Getting Tag 2
        id: tag_extractor_2
        run: |
          TAG=${{ steps.tag_extractor.outputs.latest_tag }}   
          echo "latest_tag_2=${TAG:1} " >> "$GITHUB_OUTPUT"


    outputs:
      tag: ${{ steps.tag_extractor.outputs.latest_tag }}              
      tag_2: ${{ steps.tag_extractor_2.outputs.latest_tag_2 }}      


    
  requested:
    needs: tagext
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        if: ${{  github.event_name == 'workflow_run' }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.AFTER_DEPLOY_TEST_WEBHOOK_URL }}
          content: "Requested <@&1148701924615520256> ${{ needs.tagext.outputs.tag }}"            

  pypi:
    needs: [tagext, requested]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.tagext.outputs.tag }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install dependencies
        run: |   
          pip install kot==${{ needs.tagext.outputs.tag_2 }}   kot_api==${{ needs.tagext.outputs.tag_2 }}  kot_gui==${{ needs.tagext.outputs.tag_2 }}  kot_web==${{ needs.tagext.outputs.tag_2 }}  --no-cache --upgrade


      - name: Test with pytest
        run: |
          cd tests
          pytest standards -v


  pypi_docker:
    needs: [tagext, requested]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.tagext.outputs.tag }}          
      - name: Getting Tag
        id: tag_extractor
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install dependencies
        run: |
          TAG=${{ steps.tag_extractor.outputs.latest_tag }}        
          pip install kot==${TAG:1} kot_api==${TAG:1} kot_gui==${TAG:1} kot_web==${TAG:1} --no-cache --upgrade


      - name: Test with pytest
        run: |
          cd tests
          pytest test_docker.py -v


  docker:
    needs: tagext
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.tagext.outputs.tag }}
      - name: Getting Tag
        id: tag_extractor
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install dependencies
        run: |
          TAG=${{ steps.tag_extractor.outputs.latest_tag }}         
          pip install kot==${TAG:1} kot_api==${TAG:1} kot_gui==${TAG:1} kot_web==${TAG:1} --no-cache --upgrade

      - name: Install docker
        run: |
          docker pull ghcr.io/kot-database/api:${{ steps.tag_extractor.outputs.latest_tag }}
      - name: Test with pytest
        run: |
          pytest tests/published_docker.py -v



  failure:
    runs-on: ubuntu-latest
    needs: [pypi, pypi_docker, docker]
    if: ${{ always() && (needs.pypi.result == 'failure' || needs.pypi_docker.result == 'failure' || needs.docker.result == 'failure') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Getting Tag
        id: tag_extractor
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"         
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.AFTER_DEPLOY_TEST_WEBHOOK_URL }}
          content: "failure <@&1148701924615520256> ${{ steps.tag_extractor.outputs.latest_tag }}"  


  success:
    runs-on: ubuntu-latest
    needs: [pypi, pypi_docker, docker]
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && (needs.pypi.result == 'success' || needs.pypi_docker.result == 'success' || needs.docker.result == 'success') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Getting Tag
        id: tag_extractor
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"         
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.AFTER_DEPLOY_TEST_WEBHOOK_URL }}
          content: "success ${{ steps.tag_extractor.outputs.latest_tag }}"  



  success_important:
    runs-on: ubuntu-latest
    needs: [pypi, pypi_docker, docker]
    if: ${{ github.event_name == 'workflow_run' && (needs.pypi.result == 'success' || needs.pypi_docker.result == 'success' || needs.docker.result == 'success') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Getting Tag
        id: tag_extractor
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"         
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.AFTER_DEPLOY_TEST_WEBHOOK_URL }}
          content: "success <@&1148701924615520256> ${{ steps.tag_extractor.outputs.latest_tag }}"            