name: Cloud Test Every - 15 Minute

on: 
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true
jobs:

  ubuntu:
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install kot --no-cache --upgrade
    - name: Test with pytest
      env:
        CLOUD_TEST_DATABASE_NAME: ${{ secrets.CLOUD_TEST_DATABASE_NAME }}
      run: |
        cd ..
        pytest KOT/tests/test_cloud.py -v

  macos:
    needs: ubuntu
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install kot --no-cache --upgrade
    - name: Test with pytest
      env:
        CLOUD_TEST_DATABASE_NAME: ${{ secrets.CLOUD_TEST_DATABASE_NAME }}
      run: |
        cd ..
        pytest KOT/tests/test_cloud.py -v



  windows:
    needs: macos
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install kot --no-cache --upgrade
    - name: Test with pytest
      env:
        CLOUD_TEST_DATABASE_NAME: ${{ secrets.CLOUD_TEST_DATABASE_NAME }}
      run: |
        cd ..
        pytest KOT/tests/test_cloud.py -v
