name: Cloud Test Every - 15 Minute

on: 
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true
jobs:

  run:
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('requirements/api.txt') }}-${{ hashFiles('requirements/web.txt') }}-${{ hashFiles('requirements/gui.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install kot --no-cache --upgrade
    - name: Test with pytest
      run: |
        cd ..
        pytest KOT/tests/test_cloud.py -v

