name: Cloud Test Informator

on:
  workflow_run:
    workflows: ["Cloud Test Every - 15 Minute"]
    types:
      - completed  

jobs:
  success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.CLOUD_TEST_WEBHOOK_URL }}
        content: "success"
  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.CLOUD_TEST_WEBHOOK_URL }}
        content: "failure @Admin"        