name: Comparison

on:  
  workflow_dispatch:


jobs:


  run:
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [self-hosted]
    env:
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('setups/api/requirements.txt') }}-${{ hashFiles('setups/web/requirements.txt') }}-${{ hashFiles('setups/gui/requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
        cd setups/api
        pip install .
        cd ..
        cd ..
        pip3 install redis
        sudo apt-get install redis-server -y
    - name: Comparison Sqlite
      run: |
        python3 tests/comparison_sqlite.py

    - name: Comparison Redis
      run: |
        python3 tests/comparison_redis.py

    - name: Comparison Redis Key Focused
      run: |
        python3 tests/comparison_redis_key_focused.py

