name: Deploys

on:
  workflow_run:
    workflows: ["Releases"]
    types:
      - completed  

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true
jobs:
  deploy-pypi:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: Deploys
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Build and Publish Python Packages
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine      
        python setup.py sdist
        twine upload dist/*
        cd setups/api/
        python setup.py sdist
        twine upload dist/*
        cd ..
        cd gui
        python setup.py sdist
        twine upload dist/*
        cd ..
        cd web
        python setup.py sdist
        twine upload dist/*
        cd ..


  deploy-docker:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: Deploys
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Getting Tag
      id: tag_extractor
      run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Build and Publish Docker Images
      env:
        VERSION: ${{ steps.tag_extractor.outputs.latest_tag }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        cd .. 
        docker build -t ghcr.io/onuratakan/api:latest -f KOT/docker/local/api/Dockerfile .
        docker build -t ghcr.io/onuratakan/api:$VERSION -f KOT/docker/local/api/Dockerfile .  
        docker push ghcr.io/onuratakan/api:latest
        docker push ghcr.io/onuratakan/api:$VERSION
