name: Deploys Informator

on:
  workflow_run:
    workflows: ["Deploys"]
    types:
      - completed  

jobs:
  success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
        content: "success"
  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
        content: "failure <@&1148701924615520256>"           