name: Production Informator

on:
  workflow_run:
    workflows: ["Production", "Production Custom"]
    types:
      - completed  



jobs:
  success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.PRODUCTION_WEBHOOK_URL }}
          content: "success"           



  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - uses: actions/checkout@v3


      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.PRODUCTION_WEBHOOK_URL }}
          content: "failure <@&1148701924615520256>"           
