name: Releases

on:
  workflow_run:
    workflows: ["Bump"]
    types:
      - completed
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Release
    steps:
    - uses: actions/checkout@v3
    - name: Getting Tag
      id: tag_extractor
      run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
  
    - uses: ncipollo/release-action@v1
      with:
        name: KOT ${{ steps.tag_extractor.outputs.latest_tag }}
        generateReleaseNotes: true
        tag: ${{ steps.tag_extractor.outputs.latest_tag }}